### ISSUE TITLE
name 'df_copy_num' is not defined

### ISSUE THREAD

**Issue by hyfood** [Jiung-Wen/q2-gcn-norm#3]
Dear Jiung-Wen,

It is delighted to see your plugin lunched in qiime2!

When I tried running your tutorial in qiime2-2019.10, I came across questions in the step of 
qiime gcn-norm copy-num-normalize \
  --i-table table-dada2.qza \
  --i-taxonomy taxonomy.qza \
  --o-gcn-norm-table table-normalized.qza :

First, rrnDB-5.6_pantaxa_stats_NCBI.tsv does not exist in /home/qiime2/miniconda/envs/qiime2-2019.10/lib/python3.6/site-packages/q2_gcn_norm/ . Then, I copy the  rrnDB-5.6_pantaxa_stats_NCBI.tsv to the directory, which looks good since I did not get this error message again.

Second, I got another error message : name 'df_copy_num' is not defined:

![image](https://user-images.githubusercontent.com/58621834/70371466-15e17880-191f-11ea-9158-139e136f59eb.png)

Do you have any idea what is the problem?

Thanks!

Kind regards

Hong

**Comment by Jiung-Wen** [comment]
Hi @HongYao4523685 ,

Thanks for reporting these problems! For the first one, I have added the package data in the setup file. And for the second one, it seems I accidentally deleted some codes and now I put it back. Can you re-install the plugin or copy the new ```_copy_num_normalize.py``` and replace the previous one? Please let me know if it works.

Best,
Jiung-Wen

**Comment by hyfood** [comment]
Hi Jiung-Wen,

Thanks for your reply!

I reinstalled the plugin but the two problems remained. However, it works after I copy the rrndb database in the directory and replace the new _copy_num_normalize.py.

Cheers

Hong

**Comment by Jiung-Wen** [comment]
Hi @HongYao4523685 ,

Thank you for letting me know! It turns out that I failed to upload the new anaconda package last time, and now it should work.

Again I really appreciate you for using this plugin and reporting all the bugs!

Best,
Jiung-Wen

**Comment by hyfood** [comment]
Hi Jiung-Wen,

My pleasure! Thank you for making this plugin! It is really helpful!

Cheers

Hong
