### ISSUE TITLE
How do I cite this plugin

### ISSUE THREAD

**Issue by BinhongLiu** [Jiung-Wen/q2-gcn-norm#5]
Hello !!

How do I cite this plugin ??

Greetings !!

**Comment by Jiung-Wen** [comment]
Hi @BinhongLiu 

Thank you for using the plugin. I hope you enjoy it!
So far the related paper is still under review. At this time I would appreciate if you mention this repo.

Best,
Jiung-Wen

**Comment by Jiung-Wen** [comment]
Citation info has been added.
https://github.com/Jiung-Wen/q2-gcn-norm/#citations
