### ISSUE TITLE
Won't install with qiime2 V2021.8

### ISSUE THREAD

**Issue by kalen-rasmussen** [Jiung-Wen/q2-gcn-norm#7]
Hey,
Great plug in for qiime2, but I was wondering if there was a way to get it to work with the latest version of qiime2? They moved qiime2 to python v3.8 after 2021.2 and I can not get the plug in to install anymore because of the phython v3.6 dependency.

**Comment by Jiung-Wen** [comment]
Thank you for reporting the issue and it has been resolved!
JC
